import { kea } from "../kea";

const logic = kea({
    actions: {
        doSomething: true,
        doSomethin11: true,
        doSomethin12: true,
        doSomethin13: true,
        doSomethin14: true,
        doSomethin15: true,
        doSomethin16: true,
        doSomethin17: true,
        doSomethin18: true,
        doSomethin19: true,
        doSomethin21: true,
        doSomethin22: true,
        doSomethin23: true,
        doSomethin24: true,
        doSomethin25: true,
        doSomethin26: true,
        doSomethin27: true,
        doSomethin28: true,
        doSomethin29: true,
        doSomethin31: true,
        doSomethin32: true,
        doSomethin33: true,
        doSomethin34: true,
        doSomethin35: true,
        doSomethin36: true,
        doSomethin37: true,
        doSomethin38: true,
        doSomethin39: true,
        doSomethin41: true,
        doSomethin42: true,
        doSomethin43: true,
        doSomethin44: true,
        doSomethin45: true,
        doSomethin46: true,
        doSomethin47: true,
        doSomethin48: true,
        doSomethin49: true,
        doSomethin51: true,
        doSomethin52: true,
        doSomethin53: true,
        doSomethin54: true,
        doSomethin55: true,
        doSomethin56: true,
        doSomethin57: true,
        doSomethin58: true,
        doSomethin59: true,
        doSomethin61: true,
        doSomethin62: true,
        doSomethin63: true,
        doSomethin64: true,
        doSomethin65: true,
        doSomethin66: true,
        doSomethin67: true,
        doSomethin68: true,
        doSomethin69: true,

        goSomewhere: (whereTo: string) => ({ whereTo }),
        goSomewhereElse: (whereTo: string) => {
            return { whereTo, cat: 4 }
        }
    }
})

