name: Tests

on:
    pull_request:
    # NOTE: by running on master, aside from highlight issues on master it also
    # ensures we have e.g. node modules cached for master, which can then be
    # used for branches. See https://github.com/actions/cache#cache-scopes for
    # scope details.
    push:
        branches:
            - master

jobs:
    ci-tests:
        name: Code quality checks
        runs-on: ubuntu-20.04
        steps:
            - uses: actions/checkout@v3

            - name: Install pnpm
              uses: pnpm/action-setup@v2
              with:
                  version: 7.x.x

            - name: Set up Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: 18
                  cache: pnpm

            - name: Install package.json dependencies with pnpm
              run: pnpm install --frozen-lockfile

            - name: Test with Jest
              run: pnpm test:jest

            - name: Test with TSD
              run: pnpm test:tsd

            - name: Test with TSC
              run: pnpm test:types
